### ISSUE TITLE
abc iview for kids timing out (1.6.8)

### ISSUE THREAD

**Issue by frumbert** [andybotting/xbmc-addon-abc-iview#1139]
My system is openelec current stable, which is think is kodi 14.1 ; used work, stopped about a week ago. I grepped the iview messages from my latest `kodi.log` file:

    07:30:29 T:140030579291904  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    07:30:29 T:140030579291904  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/config.xml?r=383
    07:30:29 T:140030579291904  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/categories_2013.xml
    07:30:32 T:140030579291904  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    07:30:32 T:140030579291904  NOTICE: [ABC iView v1.6.8] Getting programme from feed (abc4kids)
    07:30:32 T:140030579291904  NOTICE: [ABC iView v1.6.8] Fetching feed
    07:30:33 T:140030579291904  NOTICE: [ABC iView v1.6.8] Fetching URL: https://tviview.abc.net.au/iview/feed/lg/?keyword=abc4kids
    07:30:43 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 1/10
    07:31:04 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 2/10
    07:31:34 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 3/10
    07:32:18 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 4/10
    07:32:35 T:140031377344256  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    07:32:35 T:140031377344256  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/config.xml?r=383
    07:32:35 T:140031377344256  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/categories_2013.xml
    07:33:09 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 5/10
    07:34:09 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 6/10
    07:35:19 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 7/10
    07:36:37 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "IncompleteRead(5110 bytes read, 3082 more expected)". Attempting to retry URL fetch 8/10
    07:39:25 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 9/10
    07:40:43 T:140030579291904  NOTICE: [ABC iView v1.6.8] Error fetching URL: "IncompleteRead(966 bytes read, 7226 more expected)". Attempting to retry URL fetch 10/10
    07:40:43 T:140030579291904  NOTICE: [ABC iView v1.6.8] Traceback (most recent call last):
    07:44:31 T:140030579291904  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    07:44:31 T:140030579291904  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/config.xml?r=383
    07:44:31 T:140030579291904  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/categories_2013.xml
    08:57:29 T:140124566312704  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    08:57:29 T:140124566312704  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/config.xml?r=383
    08:57:29 T:140124566312704  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/categories_2013.xml
    08:57:34 T:140124566312704  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    08:57:34 T:140124566312704  NOTICE: [ABC iView v1.6.8] Getting programme from feed (abc4kids)
    08:57:34 T:140124566312704  NOTICE: [ABC iView v1.6.8] Fetching feed
    08:57:36 T:140124566312704  NOTICE: [ABC iView v1.6.8] Fetching URL: https://tviview.abc.net.au/iview/feed/lg/?keyword=abc4kids
    08:57:46 T:140124566312704  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 1/10
    08:58:06 T:140124566312704  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 2/10
    08:58:36 T:140124566312704  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 3/10
    08:59:16 T:140124566312704  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 4/10
    09:00:06 T:140124566312704  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 5/10
    09:00:22 T:140125036074752  NOTICE: [ABC iView v1.6.8] XBMC/Kodi 14.2 running on Linux
    09:00:22 T:140125036074752  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/config.xml?r=383
    09:00:22 T:140125036074752  NOTICE: [ABC iView v1.6.8] Fetching URL: http://www.abc.net.au/iview/xml/categories_2013.xml
    09:00:22 T:140125036074752  NOTICE: -->Python Interpreter Initialized<--
    09:00:28 T:140125441971968   ERROR: CPythonInvoker(6, /storage/.kodi/addons/plugin.video.abc_iview/default.py): script didn't stop in 5 seconds - let's kill it
    09:01:07 T:140124566312704  NOTICE: [ABC iView v1.6.8] Error fetching URL: "The read operation timed out". Attempting to retry URL fetch 6/10
    09:01:07 T:140124566312704  NOTICE: [ABC iView v1.6.8] Traceback (most recent call last):
    21:26:23 T:140684323657472  NOTICE: -->Python Interpreter Initialized<--
    21:26:29 T:140684259120896   ERROR: CPythonInvoker(6, /storage/.xbmc/addons/plugin.video.abc_iview/default.py): script didn't stop in 5 seconds - let's kill it

For instance, going directly to https://tviview.abc.net.au/iview/feed/lg/?keyword=abc4kids sometimes doesn't work; shouldn't be a timeout (I'm on 25mbit fibre). Log seems to be indicating it's not downloading the whole list in time?

**Comment by andybotting** [comment]
It's the service unfortunately :(

**Comment by frumbert** [comment]
Hmm, after a while going to https://tviview.abc.net.au/iview/feed/lg/?keyword=abc4kids comes up fine in my browser (same network).

**Comment by andybotting** [comment]
From my experience, the API will often return the result fine (e.g. in 1
second), but often it won't. In these cases, it'll time out or just return
an incomplete result.

We try to work around this by setting a shorter timeout, and retry up to 10
times. I usually find that after a couple of attempts, it's OK, but
occasionally it'll go all 10 attempts without success.

Keep trying, and eventually it should work. Unfortunately, I haven't got
any better solutions than this.

**Comment by andybotting** [comment]
I'm going to close this ticket now. I think the API has stabilised now and isn't much of a problem any more.

Thanks for reporting though.
