### ISSUE TITLE
ABC1 live stream

### ISSUE THREAD

**Issue by phantomdiorama** [andybotting/xbmc-addon-abc-iview#1268]
Would be good if the addon was updated to include the abc1 live stream

**Comment by kitten88** [comment]
deffinatly would love this for abc 1 & abc 2

**Comment by BeauGiles** [comment]
Would love to see this added.

**Comment by andybotting** [comment]
We have a new version of the iView add-on under development which switches to the mobile app API, and live streams are supported. While this is testing, you'll need to enable the development repo until it's pushed as stable.

The ZIP file for the development repository is http://aussieaddons.com/repo/repo-devel.zip and you'll find iView in there.

Would appreciate your feedback on the new version too.

cheers
