### ISSUE TITLE
SSL error on Apple TV 4 Kodi

### ISSUE THREAD

**Issue by jkingok** [andybotting/xbmc-addon-abc-iview#1297]
Installed latest version 1.6.8 and master on Kodi 17 prerelease from 20151230 on Apple TV 4.

I keep getting SSL rejections due to unable to verify certificate on tviview.abc.net.au - this is either due to SNI or missing root certificates or something since the default changed to certificate verification in Python 2.7.9+ from my Googling.

I have used the workaround in my build to change resources/lib/comm.py in the fetch_url method to add the context=ssl._create_unverified_context() in urllib2.urlopen, and import ssl at the top.

This fix works but really shouldn't be added as is (that's why this isn't really a pull request) because I need to figure out why the SSL isn't working and fix that (issue with the Kodi openssl build/list of certificates?) and also because I haven't put any checks so it will break on earlier Python versions.

Uploaded Kodi log file here:
http://xbmclogs.com/ppjmyqg8f#line-6961

**Comment by andybotting** [comment]
Good detective work so far. I'm OK if we have to put a hack in for ATV4 temporarily while we get this sorted out of need be.

I'll keep an eye on the automatic error reports too, and see if we have any related to this. I'm not sure we'll have too many for the ATV4 just yet.

Have you had this issue for any other add-ons, like Plus7?

**Comment by jkingok** [comment]
It is possible that it may happen on other addons, but as it is site dependent it might not.

As the Apple TV has native 7/10/SBS I haven't used those yet but 9 worked (will have to check but might not be using HTTPS).

**Comment by andybotting** [comment]
I had forgotten about this. Is it still a problem?

**Comment by jkingok** [comment]
Haven't tried it again since iview came to apple TV 4 officially. I'm not near the apple TV for a few days but will try to check and get back to you.
On 8 May 2016 6:49 PM, Andy Botting <notifications@github.com> wrote:I had forgotten about this. Is it still a problem?

**Comment by Mark-Hetherington** [comment]
I've just seen this issue on a 'Retropie' machine. I added the workaround as per http://odetodata.com/2015/01/https-certificate-verification-problem-in-python-2-7-9/

I think the proper way to fix this is to get the right CA certificates into the right path for Python to recognise them, but I just haven't found out how to do this. Essentially I think this is an OS problem, not a plugin problem.

```
import ssl
 
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by andybotting** [comment]
I've just pushed a fix similar to yours @Mark-Hetherington to master. I'm not really concerned about HTTPS here - I think the use of HTTPS in this case is more to try and obfuscate the actual URLs called by the mobile apps, etc to prevent third party clients like this one.

Please try out the latest master ZIP file from here:
https://github.com/andybotting/xbmc-addon-abc-iview/archive/master.zip

Let me know if that helps.

cheers

**Comment by Royv1981** [comment]
I want to install the Nlview kodi (https://seo-michael.co.uk/tutorial-how-to-install-nlview-kodi/), but the whole time I get the SSL certificates error. Can I try the master zip?

**Comment by andybotting** [comment]
@Royv1981 nothing to do with us, sorry

**Comment by andybotting** [comment]
I think this should be finally sorted out in v1.7.3
