### ISSUE TITLE
"dependencies not met" on [Legacy] OpenELEC 5.0.8 (x86_64)

### ISSUE THREAD

**Issue by cagney** [andybotting/xbmc-addon-abc-iview#1316]
More than anything else, an FYI.

When installing xbmc-addon-abc-iview on above it fails with missing dependency.  Found this in the logs:

20:22:02 T:140478475143040   DEBUG: Addon plugin.video.abc_iview requires script.common.plugin.cache version 0.0.0 which is not available

(why use the old version? 6.x is known and documented as broken with Nvidia ION graphics)

**Comment by andybotting** [comment]
This should work. OpenELEC 5 isn't that old.

While I try and get a test system up, can you try first installing the
dependency from here:

http://ftp.vim.org/ftp/mediaplayer/xbmc/addons/helix/script.common.plugin.cache/script.common.plugin.cache-2.5.6.zip

Cheers,
Andy

**Comment by andybotting** [comment]
Oh, I see now. You should really be using the XBMC Catch-up TV AU
repository and you'll get the dependencies automatically.. and updates.

If not, you'll need to install all dependencies manually to satisfy them.

**Comment by cagney** [comment]
I think I tracked it down.  The main kodi repo was "empty".  I suspect it had something to do with the machine's timezone been snafu, once that was fixed the main Kodi repo appeared and I could install:
http://kodi.wiki/view/Add-on:Common_plugin_cache
and then install iView.

Sorry for the noise.

**Comment by andybotting** [comment]
Not a problem
