### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by NigelCunningham** [andybotting/xbmc-addon-abc-iview#1333]
Hi Andy.

I'm wondering whether it would be possible to add subtitle support to the add-on. I'm willing to work on implementing it, but thought I'd ask you whether it sounds doable before I dive in - particularly since I don't see any mention of subtitles in the current code base and have enough projects on the go as it is.

Nigel

**Comment by andybotting** [comment]
Hi Nigel,
I think this would be a great addition to the iView addon. I've had a similar situation with the Plus7 addon, where someone sent me some code to add it, so I've got some familiarity with how it works.

I've never looked at the API side of things to see how the subtitles work, but if you're prepared to investigate that side of things, we can work together to get the code in.

cheers

**Comment by glennguy** [comment]
Hi Nigel,

I've had a go at adding this in pr #1367 

Cheers

Glenn

**Comment by menghoumenghou** [comment]
Hi andybotting glennguy,
I'm using openelec 6.95.3 for raspberry PI 3 and your addon for abc iview, I found the subtitle function is not working.
I turn on the subtitle option in the addon configuration and located one program which is known to have subtitle but when it is played, there is no subtitle available, if I click the subtitle button, I was given only one option which is to search and download subtitle from internet. 
could you please help to look into it or let me know how to collect logs ? thanks

**Comment by menghoumenghou** [comment]
Hi andybotting, glennguy,
   I found the subtitle file URL is now directly supplied under 
//*[@id="content"]/div/div/div[1]/div[3]/script/text()
  appreciate you can look into it, the code of building suburl may not work for some of the programs now.


A sample of portion that contains subtitle URL:

<div class="margined spaced">
            <div class="program-img">
                            <div class="video-wrapper-position">
	                
	                    <img class="episode-img" src="http://cdn.iview.abc.net.au/thumbs/460/ZX9673A007S005540577ea70ec9.62017967_1280.jpg" width="460" height="259" tabindex="-1" alt="Play episode, Bing Frog">
	                                        <div id="episode-info-bar" class="episode-info">
	                        <div class="episode-icons">
                                                                    									
                                        
                                        
                                            <img alt="Classified G" width="22" height="22" src="/assets/img/classification_g.svg" tabindex="0" role="img">
                                        
                                                                        
                                        
                                        
                                            <img alt="Closed Captions Available" width="18" height="14" src="/assets/img/cc_grey.svg" tabindex="0" role="img">
                                        

                                                                    
                                
                            </div>
                        <span class="duration" tabindex="0" role="">7 minutes</span>                            <div class="hidden">Duration 7 minutes <span aria-label="undefined"><abbr aria-hidden="true" title="undefined">undefined</abbr></span></div></div>
	                                </div>
            
                <div class="program-actions">
                                        <a href="#" class="watchlist-button" data-series-slug="bing" data-episode-house-number="ZX9673A007S00" role="button"><i class="fa fa-plus"></i><i class="fa fa-check"></i><i class="fa fa-spinner fa-spin"></i> <span>ADD TO WATCH LIST</span></a>
                    <a href="#" class="program-share-button" aria-haspopup="true"><i class="fa fa-share"></i> SHARE</a>

                                    </div>
				<div style="display:none;">
					<script type="text/javascript">
						var videoParams = {"playlist":[{"type":"program","captions":{"src-vtt":"http:\/\/iview.abc.net.au\/cc\/ZX9673A007S00MA1D1.vtt","src-xml":"http:\/\/iview.abc.net.au\/cc\/ZX9673A007S00MA1D1.xml","live":"0"},"hds-metered":"http:\/\/iviewmetered-vh.akamaihd.net\/z\/playback\/_definst_\/_video\/kids_bing_01_07_,650000,495000,205000,40746,40741,.mp4.csmil\/manifest.f4m","hds-unmetered":"http:\/\/iviewum-vh.akamaihd.net\/z\/playback\/_definst_\/_video\/kids_bing_01_07_,650000,495000,205000,40746,40741,.mp4.csmil\/manifest.f4m"}],"playlistAD":null,"href":"programs\/bing\/ZX9673A007S00","seriesHouseNumber":"ZX9673A","episodeHouseNumber":"ZX9673A007S00","mediaPath":"kids\/bing_01_07.mp4","seriesTitle":"Bing","seriesSlug":"bing","keywords":" abc4kids 4lower 4animals 4learn 4learning 4fav 4puggle 4explore 4best  ","title":"Frog","pubDate":"2016-08-03 08:17:00","eventDuration":"442","eventRating":"G","eventClassAdvice":"","captions":"http:\/\/iview.abc.net.au\/cc\/ZX9673A007S00MA1D1.xml","channel":"abc4kids","genre":"ABC Kids","live":"0"};
						var episodeHouseNumber = "ZX9673A007S00";
					</script>
				</div>
            </div>


            
                <div class="program-info" itemscope="" itemtype="http://schema.org/TVSeries">
                    <h2 class="series-title" itemprop="name">Bing</h2>
                    <div itemprop="episode" itemscope="" itemtype="http://schema.org/TVEpisode">
                        <span class="episode-title" itemprop="name">Frog</span>
                        <meta itemprop="episodeNumber" content="7">
                        <div class="genre">
                                                                                        <a class="event-genre" href="http://www.abc.net.au/abcforkids/shows/s4097964.htm"><i class="fa fa-globe"></i> GO TO WEBSITE</a>
                                                    </div>
                        <div class="episode-description" itemprop="description">
                            <p>Bing finds a frog in the garden and wants to keep it so he and Sula make the frog a 'house' in a bucket. But froggy doesn't like her new home and hops out.</p>
                        </div>
                        <div class="availability">
                                                                <a class="channel-logo" href="/channel/abc4kids"><img src="/assets/img/channel_abc4kids_80x42.jpg" width="80" alt="abc4kids"></a>
                                                        This episode was published 15 hours ago and is available until 8:17am on 7 Aug 2016. File size 37&nbsp;MB                        </div>
                    </div>
                </div>

            
            <div id="program-share-links" role="menu" aria-label="Social Media Share Links" style="display: none;">
                <a href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fiview.abc.net.au%2Fprograms/bing/ZX9673A007S00&amp;t=Bing%20Frog" role="menuitem" tabindex="0" target="_blank"><img src="/assets/img/share_fb_icon.png" alt="Share on Facebook"></a>
                <a href="http://twitter.com/intent/tweet?text=http%3A%2F%2Fiview.abc.net.au%2Fprograms/bing/ZX9673A007S00" role="menuitem" tabindex="0" target="_blank"><img src="/assets/img/share_twitter_icon.png" alt="Share on Twitter"></a>
                <a href="https://plus.google.com/share?url=http%3A%2F%2Fiview.abc.net.au%2Fprograms/bing/ZX9673A007S00" role="menuitem" tabindex="0" target="_blank"><img src="/assets/img/share_gplus_icon.png" alt="Share on Google+"></a>
            </div>

            
            
        </div>

**Comment by glennguy** [comment]
Hi menghoumenghou

Looking at your code above it looks like that's from the desktop API - this addon uses a different API (not sure which one, Andy would be able to tell you) that gives us some information in XML format like so:
```
<item>
      <guid isPermaLink="true">http://tviview.abc.net.au/programs/bing/ZX9673A012S00</guid>
      <link>http://tviview.abc.net.au/programs/bing/ZX9673A012S00</link>
      <title><![CDATA[Bing]]></title>
      <subtitle><![CDATA[Here I Go]]></subtitle>
      <description><![CDATA[Bing and Pando discover a new climbing frame at the playground. It's got climbing bits, tippy bits and even wobbly bridge. But when Bing gets to the top of the slide it's too scary for him to go down.]]></description>
      <pubDate>Mon, 08 Aug 2016 08:17:00 +1000</pubDate>
      <media:content type="video/x-flv" bitrate="650" duration="442"/>
      <media:thumbnail url="http://cdn.iview.abc.net.au/thumbs/i/388/ZX9673A012S00544472857b2e95.37057773_1280.jpg"/>
      <media:player url="http://tviview.abc.net.au/programs/bing/ZX9673A012S00"/>
      <media:restriction relationship="allow" type="country">au</media:restriction>
      <abc:videoAsset><![CDATA[https://abcsecurehttp-a.akamaihd.net/playback/_definst_/_video/kids_bing_01_12_650000.mp4?d=lg&a=56757d3458569a52a5e96664cb8a412f]]></abc:videoAsset>
      <abc:expireDate>Mon, 22 Aug 2016 08:17:00 +1000</abc:expireDate>
    </item>
```

Now instead of the subtitle file being based upon the mp4 file name it is based on the filename in the 'link' tag, with 'MA1D1' appended. We still have to guess the filename. I've got it working on my end, just need to do a little bit of testing and I'll make a new PR for it. Hopefully later today.

**Comment by menghoumenghou** [comment]
Hi glennguy,
 thanks for your reply, I tried a few programs recently and found out iview is not consistent in naming subtitle files, some programs are using mp4 file name like before, some are using the "MA1D1" suffixed file name, I even ran into some program which has multiple versions of subtitle like [this one](http://cdn.iview.abc.net.au/programs/how-drugs-work/ZX9610A001S00) , its subtitle is named howdrugswork_01_01_v2.xml.  The API Andy was using is Yahoo media rss service, it may not parse the information now embedded in script section of the page:

                <script type="text/javascript">
                    var videoParams = {"playlist":[{"type":"program","captions":{"src-vtt":"http:\/\/iview.abc.net.au\/cc\/ZX9673A007S00MA1D1.vtt","src-xml":"http:\/\/iview.abc.net.au\/cc\/ZX9673A007S00MA1D1.xml","live":"0"},"hds-metered":"http:\/\/iviewmetered-vh.akamaihd.net\/z\/playback\/_definst_\/_video\/kids_bing_01_07_,650000,495000,205000,40746,40741,.mp4.csmil\/manifest.f4m","hds-unmetered":"http:\/\/iviewum-vh.akamaihd.net\/z\/playback\/_definst_\/_video\/kids_bing_01_07_,650000,495000,205000,40746,40741,.mp4.csmil\/manifest.f4m"}],"playlistAD":null,"href":"programs\/bing\/ZX9673A007S00","seriesHouseNumber":"ZX9673A","episodeHouseNumber":"ZX9673A007S00","mediaPath":"kids\/bing_01_07.mp4","seriesTitle":"Bing","seriesSlug":"bing","keywords":" abc4kids 4lower 4animals 4learn 4learning 4fav 4puggle 4explore 4best  ","title":"Frog","pubDate":"2016-08-03 08:17:00","eventDuration":"442","eventRating":"G","eventClassAdvice":"","captions":"http:\/\/iview.abc.net.au\/cc\/ZX9673A007S00MA1D1.xml","channel":"abc4kids","genre":"ABC Kids","live":"0"};
                    var episodeHouseNumber = "ZX9673A007S00";
                </script>

   Currently I'm using a stupid way to solve this, I use thumbnail URL to generate another subtitle file url in play.py :
suburl2 = (config.subtitle_url+p.thumbnail[p.thumbnail.rfind('/')+1:p.thumbnail.rfind('/')+14]+"MA1D1"+".xml")
and do the subfile download thing again in case downloading by the mp4 file name hits 404. it works for me, but it doesn't cope with the multiple-version subtitle situation.

**Comment by glennguy** [comment]
I've come up with a solution in #1909, ended up getting the data from where you initially suggested. Luckily the URL for the page is what's in the 'link' tag, so no guesswork involved! Have a look and let me know how you go. I've tested a bunch including the examples you gave and it's working good.

**Comment by menghoumenghou** [comment]
Thanks Glenn, I tried a few and all of them are working good.
