### ISSUE TITLE
Kodi playback broken?

### ISSUE THREAD

**Issue by inspector71** [andybotting/xbmc-addon-abc-iview#1351]
Hi

Had a look around and can't be sure some sort of bot hasn't already reported this, but it appears that 1.6.8 is unable to play any streams on Raspberry Pi 2 within OpenELEC 6.0.3 at least.

Partial log information here:

http://pastebin.com/1HLw54iN

Let me know if you need more debugging/testing help.

**Comment by andybotting** [comment]
I've just successfully tested this setup. Same versions also on an RPi2.

Haven't had a good look at your log yet though. Did you manage to send
through an automatic bug report?

Cheers

**Comment by andybotting** [comment]
Unfortunately, the log file doesn't indicate what went wrong here. Can you confirm you're accessing iView from Australia?

**Comment by inspector71** [comment]
Hi
Apologies for the delay in my response.
I've a vague recollection of seeing some semi-private information in some automated reports somewhere so that option concerns me enough to not take it up at this point.
Regardless, it appears the issue may be local/temporary or due to dated/inaccurate provider data after all.
Apologies for wasting time. I believe this issue can be closed.
Oh yeah and yes, I was accessing the iView content within Australia.
