### ISSUE TITLE
Unable to fetch programs list

### ISSUE THREAD

**Issue by 123host** [andybotting/xbmc-addon-abc-iview#245]
Hey Andy

Just installed plugin on Kobi.  I get a list of categories but then an error when trying to load list of shows within category.

unable to fetch_programs_list(31) Plug in is out of date, update to version 1.63 (or words to that effect)

But I just downloaded from here and plugin indicates it is Ver 1.64

**Comment by andybotting** [comment]
I can see that iView is having a few issues right now - lots of timeouts and some 404s. I've taken this opportunity to fix up some of the error handling and reporting.

I'll probably push a new version of the addon to the Catchup TV AU repository over the next few days.

Thanks

**Comment by Bofeni** [comment]
Hi Andy,

Similar issues here, and has been like this for a few weeks now. 
The error message I usually get is 'the read operation timed out 'make_series_list(35)', other times it is incomplete read, xxxx bytes read, expecting yyyy bytes. 

This only seems to be a problem in the larger categories for some reason, like abc4kids, abc1 and some others. And it's intermittent too. For example the most prblematic for us is abc4kids, and it seems to be an issue for several minutes/hours at a time. However if I paste the url that its trying to fetch into chrome it loads the xml file completely in a few seconds

Here is a link to the relevant part of my log - http://pastebin.com/S0y41wbK

Hope this helps

Glenn

**Comment by andybotting** [comment]
Yeah, that's basically what I was seeing last night.. but I was also getting errors pulling the index with cURL. At this stage, it looks like ABC's servers might have been failing at high load (as I can't fault it now at 8:30am).

I'm thinking I might add an automatic retry if there is a failure of any type, along with a shorter timeout. I think that should get around the intermittent failures in a completely transparent way.
